[package]
name = "google-authenticator"
version = "0.1.0"
authors = ["hans <hans@hansk.org>"]
repository = "https://github.com/hanskorg/google-authenticator-rust.git"
homepage = "https://github.com/hanskorg/google-authenticator-rust.git"
license = "MIT"
readme = "https://github.com/hanskorg/google-authenticator-rust/blob/master/README.md"
documentation = "This Rust crate can be used to interact with the Google Authenticator mobile app for 2-factor-authentication."

[dependencies]
rand = "0.4"
base32 = "0.3.1"
hmac-sha1 = "0.1.3"